# Generated by Django 4.1.3 on 2022-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesList', '0002_rename_procuts_recipe_products_recipe_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
